### ISSUE TITLE
Conexão com a api

### ISSUE THREAD

**Issue by geich** [MarthinKorb/challenge-zaply#1]
Fala Marthin!

Olha só, estou tentando conectar com a api e não está dando certo. 

Fiz o processo de instalação pelo **docker** e rodei os **migrations**, até aqui tudo certo!

Porém no [zaply-web](https://github.com/MarthinKorb/challenge-zaply/tree/master/zaply-web) os produtos só retornam quando eu uso a **Fake API**

Nos [docs ](http://localhost:3000/api-docs)também não está retornando nada pra mim na consulta `GET /products`.

Falta mais algum passo no [zaply-server](https://github.com/MarthinKorb/challenge-zaply/tree/master/zaply-web)?

**Comment by MarthinKorb** [comment]
Podemos talvez fazer uma ligação para tirar essas dúvidas?

**Comment by MarthinKorb** [comment]
Opa.... Você tentou criar algum produto?
o retorno no get/products, está retornando erro ou um array vazio?

**Comment by MarthinKorb** [comment]
Outra coisa, conseguiu rodar o comando 'yarn dev' e ter no console a frase: 'Server running on port 3000'?

**Comment by geich** [comment]
Ah não tinha entendido que era necessário criar os produtos. Deu certo, obrigado!

**Comment by MarthinKorb** [comment]
Show... Este banco de dados está vazio... Criei ele para operar da mesma maneira que a API Fake...
Qualquer dúvida que surja, fico à disposição!
